/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package app;
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.*;
import javax.swing.table.TableRowSorter;
import java.util.logging.Level;
import java.util.logging.Logger;
/**
 *
 * @author ANAGHA
 */
public class project extends javax.swing.JFrame {

    /**
     * Creates new form project
     */
    private ResultSet rs;
    

    public project() {
        initComponents();
        try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/miniproject","root","123456");
           Statement stmt = con.createStatement(ResultSet.TYPE_SCROLL_INSENSITIVE, ResultSet.CONCUR_READ_ONLY);
           

          rs =stmt.executeQuery("select * from studentroject; ");
            if(rs.next())
            {
                  t1.setText(String.valueOf(rs.getInt(1)));
                 t2.setText(rs.getString(2));
                  t3.setText(rs.getString(3));
                 t4.setText(String.valueOf(rs.getInt(4)));
                  t5.setText(rs.getString(5));
                   t6.setText(rs.getString(6));
                    t7.setText(rs.getString(7));
                     t8.setText(String.valueOf(rs.getInt(8)));
        }
                        
            }
            catch(Exception e)  {
               
                System.out.println(e);
            }  

    }
    private void updateUIWithResultSetValues() {
    try {
        // Assuming t1, t2, t3, ..., t8 are your JTextFields or similar components
        t1.setText(String.valueOf(rs.getInt(1)));
        t2.setText(rs.getString(2));
        t3.setText(rs.getString(3));
        t4.setText(String.valueOf(rs.getInt(4)));
        t5.setText(rs.getString(5));
        t6.setText(rs.getString(6));
        t7.setText(rs.getString(7));
        t8.setText(String.valueOf(rs.getInt(8)));
    } catch (SQLException ex) {
        ex.printStackTrace();
        JOptionPane.showMessageDialog(this, "Error updating UI with ResultSet values: " + ex.getMessage());
    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton7 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jTextField1 = new javax.swing.JTextField();
        projectsrc = new javax.swing.JButton();
        fetchpro = new javax.swing.JButton();
        backpro = new javax.swing.JButton();
        add = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        t1 = new javax.swing.JTextField();
        t3 = new javax.swing.JTextField();
        t2 = new javax.swing.JTextField();
        t7 = new javax.swing.JTextField();
        t4 = new javax.swing.JTextField();
        t8 = new javax.swing.JTextField();
        t5 = new javax.swing.JTextField();
        t6 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        update = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        remove = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        FIRSTT = new javax.swing.JButton();

        jButton7.setBackground(new java.awt.Color(255, 204, 255));
        jButton7.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton7.setText("REMOVE");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "PROJECT_ID", "DOMAIN", "TYPE", "SEMESTER", "LINK", "PROJECT NAME", "REVIEW", "BATCH_ID"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        projectsrc.setBackground(new java.awt.Color(255, 204, 255));
        projectsrc.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        projectsrc.setText("SEARCH");
        projectsrc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                projectsrcMouseClicked(evt);
            }
        });
        projectsrc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                projectsrcActionPerformed(evt);
            }
        });
        projectsrc.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                projectsrcKeyReleased(evt);
            }
        });

        fetchpro.setBackground(new java.awt.Color(255, 204, 255));
        fetchpro.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        fetchpro.setText("FETCH");
        fetchpro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fetchproActionPerformed(evt);
            }
        });

        backpro.setBackground(new java.awt.Color(255, 204, 255));
        backpro.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        backpro.setText("BACK");
        backpro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backproActionPerformed(evt);
            }
        });

        add.setBackground(new java.awt.Color(255, 204, 255));
        add.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        add.setText("ADD");
        add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addActionPerformed(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(255, 204, 255));
        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setText("PROJECT_ID");

        jLabel2.setBackground(new java.awt.Color(255, 204, 255));
        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel2.setText("TYPE");

        jLabel3.setBackground(new java.awt.Color(255, 204, 255));
        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel3.setText("LINK");

        jLabel4.setBackground(new java.awt.Color(255, 204, 255));
        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel4.setText("DOMAIN");

        jLabel5.setBackground(new java.awt.Color(255, 204, 255));
        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel5.setText("SEMESTER");

        jLabel6.setBackground(new java.awt.Color(255, 204, 255));
        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel6.setText("REVIEW");

        jLabel7.setBackground(new java.awt.Color(255, 204, 255));
        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel7.setText("PROJECT NAME");

        jLabel8.setBackground(new java.awt.Color(255, 204, 255));
        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel8.setText("BATCH_ID");

        jButton2.setBackground(new java.awt.Color(255, 204, 255));
        jButton2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton2.setText("PREVIOUS");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(255, 204, 255));
        jButton3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton3.setText("NEXT");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        update.setBackground(new java.awt.Color(255, 204, 255));
        update.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        update.setText("UPDATE");
        update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateActionPerformed(evt);
            }
        });

        jButton5.setBackground(new java.awt.Color(255, 204, 255));
        jButton5.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton5.setText("CLEAR");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        remove.setBackground(new java.awt.Color(255, 204, 255));
        remove.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        remove.setText("REMOVE");
        remove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeActionPerformed(evt);
            }
        });

        jButton8.setBackground(new java.awt.Color(255, 204, 255));
        jButton8.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton8.setText("LAST");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        FIRSTT.setBackground(new java.awt.Color(255, 204, 255));
        FIRSTT.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        FIRSTT.setText("FIRST");
        FIRSTT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FIRSTTActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(43, 43, 43)
                        .addComponent(projectsrc))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(t4, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(59, 59, 59))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(t1, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(t2, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(t3, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(t7, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(t8, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(t6, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(t5, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(add, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(update))
                        .addGap(57, 57, 57)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(remove)
                            .addComponent(jButton8)
                            .addComponent(jButton5))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(FIRSTT)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(fetchpro)
                                .addGap(69, 69, 69)
                                .addComponent(backpro))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton3)
                                .addGap(83, 83, 83)
                                .addComponent(jButton2)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 867, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(projectsrc)
                        .addComponent(fetchpro)
                        .addComponent(backpro)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addComponent(t1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel1)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addComponent(jLabel2)
                                .addGap(12, 12, 12)
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel3)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(t2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel4))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(t3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(t4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(update)
                                            .addComponent(jButton5))
                                        .addGap(20, 20, 20)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(t5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(t6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel7))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(t7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel6))
                                        .addGap(11, 11, 11)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel8)
                                            .addComponent(t8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(FIRSTT)
                                            .addComponent(jButton8))
                                        .addGap(40, 40, 40)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jButton2)
                                            .addComponent(jButton3))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(add)
                            .addComponent(remove))
                        .addContainerGap())))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fetchproActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fetchproActionPerformed
DefaultTableModel model=(DefaultTableModel) jTable1.getModel();
   /*String url="jdbc:mysql://localhost:3306/miniproject";
    String user="root";
    String pwd="123456";
    String query ="select* from miniproject";*/
    /*var batch_id =batchname.getText();*/
     try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/miniproject","root","123456");
            Statement stmt=con.createStatement();
       
            ResultSet rs=stmt.executeQuery("select * from studentroject; ");
            while(rs.next())
            {
                int projectid=rs.getInt("project_id");
                String domain=rs.getString("domain");
                String type=rs.getString("type");
                int semester=rs.getInt("semester");
                String link_report=rs.getString("link");
                String name=rs.getString("project_name");
                String Review=rs.getString("review");
                 int batch_id=rs.getInt("batch_id");
                model.addRow(new Object[] {projectid,domain,type,semester,link_report,name,Review,batch_id});
                
            }
            rs.close();
            stmt.close();
            
            
            }
            catch(Exception e)  {
                JOptionPane.showMessageDialog(this, e.getMessage());
                
            }  


        // TODO add your handling code here:
    }//GEN-LAST:event_fetchproActionPerformed

    private void projectsrcKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_projectsrcKeyReleased



        // TODO add your handling code here:
    }//GEN-LAST:event_projectsrcKeyReleased

    private void backproActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backproActionPerformed
this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_backproActionPerformed

    private void projectsrcMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_projectsrcMouseClicked
     DefaultTableModel model=(DefaultTableModel) jTable1.getModel();
 TableRowSorter<DefaultTableModel> obj1=new TableRowSorter<>(model);
 jTable1.setRowSorter(obj1);
 obj1.setRowFilter(RowFilter.regexFilter(jTextField1.getText()));
    // TODO add your handling code here:
    }//GEN-LAST:event_projectsrcMouseClicked

    private void FIRSTTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FIRSTTActionPerformed
  try {
        if (rs != null && rs.first()) {
            t1.setText(String.valueOf(rs.getInt(1)));
            t2.setText(rs.getString(2));
            t3.setText(rs.getString(3));
            t4.setText(String.valueOf(rs.getInt(4)));
            t5.setText(rs.getString(5));
            t6.setText(rs.getString(6));
            t7.setText(rs.getString(7));
            t8.setText(String.valueOf(rs.getInt(8)));
        } else {
            JOptionPane.showMessageDialog(this, "ResultSet is either null or at the first row.");
        }
    } catch (SQLException ex) {
        Logger.getLogger(batch.class.getName()).log(Level.SEVERE, null, ex);
        JOptionPane.showMessageDialog(this, "Error navigating ResultSet: " + ex.getMessage());
    }


        // TODO add your handling code here:
    }//GEN-LAST:event_FIRSTTActionPerformed

    private void addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addActionPerformed

        
        
    /*stm.setInt(1, Integer.parseInt(t1.getText()));
    stm.setString(2, t2.getText());
    stm.setString(3, t3.getText());
    stm.setInt(4, Integer.parseInt(t4.getText()));
    stm.setString(5, t5xtField.getText());
    stm.setString(7, t6.getText());
    stm.setInt(8, Integer.parseInt(t7.getText()));
String status = t8.getText();
        try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/miniproject", "root", "123456");

            String query = "INSERT INTO studentproject (project_id, domain, type, semester, link, project_name, review, batch_id) VALUES (?, ?, ?, ?, ?, ?, ?, ?)";
            PreparedStatement stm = con.prepareStatement(query);

            // Set values based on your input fields
            stm.setInt(1, project_id);
            stm.setString(2, domain);
            stm.setString(3, yourTypeValue);
            stm.setInt(4, yourSemesterValue);
            stm.setString(5, yourLinkValue);
            stm.setString(6, yourProjectNameValue);
            stm.setString(7, yourReviewValue);
            stm.setInt(8, yourBatchIdValue);

            int rowsInserted = stm.executeUpdate();
            if (rowsInserted > 0) {
                JOptionPane.showMessageDialog(this, "Record added successfully");
            } else {
                JOptionPane.showMessageDialog(this, "Failed to add record");
            }

            stm.close();
            con.close();
        } catch (ClassNotFoundException | SQLException e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }*/try {
    Class.forName("com.mysql.jdbc.Driver");
    Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/miniproject", "root", "123456");

    // Assuming t1, t2, t3, ..., t8 are your JTextFields or similar components
    int project_id = Integer.parseInt(t1.getText());
    String domain = t2.getText();
    String yourTypeValue = t3.getText(); // Replace with the appropriate way to get the type value
    int yourSemesterValue = Integer.parseInt(t4.getText());
    String yourLinkValue = t5.getText();
    String yourProjectNameValue = t6.getText();
    String yourReviewValue = t7.getText();
    int yourBatchIdValue = Integer.parseInt(t8.getText());

    String query = "INSERT INTO studentroject (project_id, domain, type, semester, link, project_name, review, batch_id) VALUES (?, ?, ?, ?, ?, ?, ?, ?)";
    PreparedStatement stm = con.prepareStatement(query);
    stm.setInt(1, project_id);
    stm.setString(2, domain);
    stm.setString(3, yourTypeValue);
    stm.setInt(4, yourSemesterValue);
    stm.setString(5, yourLinkValue);
    stm.setString(6, yourProjectNameValue);
    stm.setString(7, yourReviewValue);
    stm.setInt(8, yourBatchIdValue);

    int rowsAffected = stm.executeUpdate();

    if (rowsAffected > 0) {
        JOptionPane.showMessageDialog(this, "Project added successfully");
        // Assuming rs is a ResultSet, update it with the new data
        rs = stm.executeQuery("SELECT * FROM studentroject WHERE project_id = " + project_id);
        if (rs.next()) {
            updateUIWithResultSetValues();
        }
    } else {
        JOptionPane.showMessageDialog(this, "Error adding project");
    }

    // Clear text fields
    t1.setText(null);
    t2.setText(null);
    t3.setText(null);
    t4.setText(null);
    t5.setText(null);
    t6.setText(null);
    t7.setText(null);
    t8.setText(null);

    // Close the connection
    con.close();
} catch (Exception e) {
    JOptionPane.showMessageDialog(this, e.getMessage());
}
    


        // TODO add your handling code here:
    }//GEN-LAST:event_addActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
t1.setText("");
  t2.setText("");
  t3.setText("");
  t4.setText("");
  t5.setText("");
  t6.setText("");
  t7.setText("");
  t8.setText("");

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed



 try {
        if (rs != null && rs.last()) {
            updateUIWithResultSetValues();
        } else {
            JOptionPane.showMessageDialog(this, "ResultSet is either null or empty.");
        }
    } catch (SQLException ex) {
        ex.printStackTrace();
        JOptionPane.showMessageDialog(this, "Error navigating ResultSet: " + ex.getMessage());
    }
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
try {
        if (rs != null && rs.previous()) {
            updateUIWithResultSetValues();
        } else {
            JOptionPane.showMessageDialog(this, "No previous row available.");
        }
    } catch (SQLException ex) {
        ex.printStackTrace();
        JOptionPane.showMessageDialog(this, "Error navigating ResultSet: " + ex.getMessage());
    }


        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
try {
        if (rs != null && rs.next()) {
            updateUIWithResultSetValues();
        } else {
            JOptionPane.showMessageDialog(this, "No next row available.");
        }
    } catch (SQLException ex) {
        ex.printStackTrace();
        JOptionPane.showMessageDialog(this, "Error navigating ResultSet: " + ex.getMessage());
    }
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void removeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeActionPerformed

try {
    Class.forName("com.mysql.jdbc.Driver");
    Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/miniproject", "root", "123456");

    // Assuming t1 is your JTextField or similar component containing the project_id to be removed
    int project_idToRemove = Integer.parseInt(t1.getText());

    String query = "DELETE FROM studentroject WHERE project_id = ?";
    PreparedStatement stm = con.prepareStatement(query);
    stm.setInt(1, project_idToRemove);

    int rowsAffected = stm.executeUpdate();

    if (rowsAffected > 0) {
        JOptionPane.showMessageDialog(this, "Project removed successfully");

        // Assuming rs is a ResultSet, update it with the new data
        rs = stm.executeQuery("SELECT * FROM studentroject");
        if (rs.next()) {
            updateUIWithResultSetValues();
        } else {
            // No more rows in ResultSet, clear the UI
           
        }
    } else {
        JOptionPane.showMessageDialog(this, "Error removing project");
    }

    // Clear text fields
    t1.setText(null);

    // Close the connection
    con.close();
} catch (Exception e) {
    JOptionPane.showMessageDialog(this, e.getMessage());
}



        // TODO add your handling code here:
    }//GEN-LAST:event_removeActionPerformed

    private void updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateActionPerformed



try {
    Class.forName("com.mysql.jdbc.Driver");
    Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/miniproject", "root", "123456");

    // Assuming t1, t2, t3, t4, t5, t6, t7, and t8 are your JTextFields or similar components containing the updated values
    int project_idToUpdate = Integer.parseInt(t1.getText());
    String domain = t2.getText();
    String type = t3.getText();
    int semester = Integer.parseInt(t4.getText());
    String link = t5.getText();
    String project_name = t6.getText();
    String review = t7.getText();
    int batch_id = Integer.parseInt(t8.getText());

    String query = "UPDATE studentroject SET domain = ?, type = ?, semester = ?, link = ?, project_name = ?, review = ?, batch_id = ? WHERE project_id = ?";
    PreparedStatement stm = con.prepareStatement(query);
    stm.setString(1, domain);
    stm.setString(2, type);
    stm.setInt(3, semester);
    stm.setString(4, link);
    stm.setString(5, project_name);
    stm.setString(6, review);
    stm.setInt(7, batch_id);
    stm.setInt(8, project_idToUpdate);

    int rowsAffected = stm.executeUpdate();

    if (rowsAffected > 0) {
        JOptionPane.showMessageDialog(this, "Project updated successfully");

        // Assuming rs is a ResultSet, update it with the new data
        rs = stm.executeQuery("SELECT * FROM studentroject");
        if (rs.next()) {
            updateUIWithResultSetValues();
        } else {
            // No more rows in ResultSet, clear the UI
          
        }
    } else {
        JOptionPane.showMessageDialog(this, "Error updating project");
    }

    // Clear text fields
    t1.setText(null);
    t2.setText(null);
    t3.setText(null);
    t4.setText(null);
    t5.setText(null);
    t6.setText(null);
    t7.setText(null);
    t8.setText(null);

    // Close the connection
    con.close();
} catch (Exception e) {
    JOptionPane.showMessageDialog(this, e.getMessage());
}        // TODO add your handling code here:
    }//GEN-LAST:event_updateActionPerformed

    private void projectsrcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_projectsrcActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_projectsrcActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(project.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(project.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(project.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(project.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new project().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton FIRSTT;
    private javax.swing.JButton add;
    private javax.swing.JButton backpro;
    private javax.swing.JButton fetchpro;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JButton projectsrc;
    private javax.swing.JButton remove;
    private javax.swing.JTextField t1;
    private javax.swing.JTextField t2;
    private javax.swing.JTextField t3;
    private javax.swing.JTextField t4;
    private javax.swing.JTextField t5;
    private javax.swing.JTextField t6;
    private javax.swing.JTextField t7;
    private javax.swing.JTextField t8;
    private javax.swing.JButton update;
    // End of variables declaration//GEN-END:variables
}
